// <auto-generated />
using System;
using IdentitySampleApi.DataAccessLayer.ApplicationContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdentitySampleApi.DataAccessLayer.Migrations
{
    [DbContext(typeof(DefaultDatabaseContext))]
    [Migration("20191007074905_First-Migration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentitySample.EntityLayer.Entities.SubThing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<DateTime>("RemoveDate");

                    b.Property<Guid?>("ThingId");

                    b.HasKey("Id");

                    b.HasIndex("ThingId");

                    b.ToTable("SubThing");
                });

            modelBuilder.Entity("IdentitySample.EntityLayer.Entities.Thing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<DateTime>("RemoveDate");

                    b.HasKey("Id");

                    b.ToTable("Thing");
                });

            modelBuilder.Entity("IdentitySample.EntityLayer.Entities.SubThing", b =>
                {
                    b.HasOne("IdentitySample.EntityLayer.Entities.Thing")
                        .WithMany("SubThings")
                        .HasForeignKey("ThingId");
                });
#pragma warning restore 612, 618
        }
    }
}
